#! /bin/bash
#
# Copyright 2010-2015 CERN and Helsinki Institute of Physics.
# This software is distributed under the terms of the
# GNU General Public License version 3 (GPL Version 3),
# copied verbatim in the file LICENCE.md. In applying this
# license, CERN does not waive the privileges and immunities granted to it
# by virtue of its status as an Intergovernmental Organization
# or submit itself to any jurisdiction.
#
# Project website: http://arcpic.web.cern.ch/
# Developers: Helga Timko, Kyrre Sjobak, Lotta Mether
#

if [ $# -eq 0 ] || [ $# -gt 5 ]; then
    echo "Usage: Reads in up to 4 folder names and makes gle analysis from arcpic readme output. 
Note: Folder needs to be one step under current folder
      Output filename hardcoded to 'readme.out'
      You might want to manually rename the png files at the bottom if your folder names are long
      Last input is interpreted as desired name for plots!!!"
    exit
fi

i=0
folders=($@)
let num=$#-1
string=${folders[$num]}
echo $string

mkdir Ncomp
cd Ncomp

rm -rf Ncompare.gle
rm -rf Ncompare_eCup.gle
rm -rf Ncompare_Cu.gle
rm -rf Ncompare_Cu.gle-tmp

echo "! Gle file generated by gle.el
size 28 20
set lwidth 0.04
set hei 0.5
set font psh
begin graph

" >> Ncompare.gle

cp Ncompare.gle Ncompare_eCup.gle
cp Ncompare.gle Ncompare_Cu.gle-tmp


# Get N's #

while [ $i -lt $num ]; do

    folder=${folders[$i]}
    echo $folder
    file="../$folder/readme.out"
    nav=`grep ' nav_dt:' $file | awk '{print $3;}'`
    nav0=`grep ' nav_start:' $file | awk '{print $3;}'`
    navt=`grep ' nav_time:' $file | awk '{print $3;}'`
    dt=`grep ' dt:' $file | awk '{print $3;}'`
    nref=`grep ' n_ref:' $file | awk '{print $3;}'`
    tstep=`echo $nav $dt $nref | awk '{tstep=$1*$2/(56414.6*sqrt($3))*1e9; printf "%15.10f", tstep;}'` # tstep in [ns]
    t0=`echo $nav0 $navt $dt $nref | awk '{t0=($1+$2)*$3/(56414.6*sqrt($4))*1e9; printf "%15.10f", t0;}'` # t0 in [ns]
    Tref=`grep ' T_ref:' $file | awk '{print $3;}'`
    Ndb=`grep ' Ndb:' $file | awk '{print $3;}'`
    Ldb=`echo $Tref $nref | awk '{Ldb=7.43e2*sqrt($1/$2); printf "%15.10f", Ldb;}'` 
    nsp=`echo $nref $Ldb $Ndb | awk '{nsp=$1*$2^3/$3; printf "%15.10f", nsp;}'`
    echo " Timestep: $tstep ns"

    grep 'e- ' $file | awk -v "ts=$tstep" -v "t0=$t0" -v "i=0" -v "ns=$nsp" '{printf "%15.10f  %15.10f\n", ts*i+t0, $5*ns; i++;}' > $folder-N_e.dat
    grep 'Cu+' $file | awk -v "ts=$tstep" -v "t0=$t0" -v "i=0" -v "ns=$nsp" '{printf "%15.10f  %15.10f\n", ts*i+t0, $4*ns; i++;}' > $folder-N_Cup.dat
    grep 'Cu ' $file | awk -v "ts=$tstep" -v "t0=$t0" -v "i=0" -v "ns=$nsp" '{printf "%15.10f  %15.10f\n", ts*i+t0, $5*ns; i++;}' > $folder-N_Cu.dat

    let i=i+1
done


# Write gle files #

color1e="mediumblue"
color2e="royalblue"
color3e="skyblue"
color4e="midnightblue"
color1Cup="darkmagenta"
color2Cup="mediumvioletred"
color3Cup="hotpink"
color4Cup="indigo"
color1Cu="forestgreen"
color2Cu="limegreen"
color3Cu="lawngreen"
color4Cu="darkgreen"

i=0

if [ $i -lt $num ]; then
echo "
   data ${folders[$i]}-N_e.dat d1=c1,c2  
   d1 line lstyle 2 marker circle msize 0.3 color $color1e key \"${folders[$i]}: e^-\" " >> Ncompare.gle 
tail -n 3 Ncompare.gle >> Ncompare_eCup.gle
fi
let i=i+1

if [ $i -lt $num ]; then
echo "
   data ${folders[$i]}-N_e.dat d2=c1,c2  
   d2 line lstyle 2 marker triangle msize 0.3 color $color2e key \"${folders[$i]}: e^-\" " >> Ncompare.gle 
tail -n 3 Ncompare.gle >> Ncompare_eCup.gle
fi
let i=i+1

if [ $i -lt $num ]; then
echo "
   data ${folders[$i]}-N_e.dat d3=c1,c2  
   d3 line lstyle 2 marker diamond msize 0.3 color $color3e key \"${folders[$i]}: e^-\" " >> Ncompare.gle
tail -n 3 Ncompare.gle >> Ncompare_eCup.gle
fi
let i=i+1

if [ $i -lt $num ]; then
echo "
   data ${folders[$i]}-N_e.dat d4=c1,c2  
   d4 line lstyle 2 marker square msize 0.3 color $color4e key \"${folders[$i]}: e^-\" " >> Ncompare.gle
tail -n 3 Ncompare.gle >> Ncompare_eCup.gle
fi

###
i=0
###

if [ $i -lt $num ]; then
echo "
   data ${folders[$i]}-N_Cup.dat d5=c1,c2
   d5 line lstyle 3 marker circle msize 0.3 color $color1Cup key \"${folders[$i]}: Cu^+\" " >> Ncompare.gle 
tail -n 3 Ncompare.gle >> Ncompare_eCup.gle
fi
let i=i+1

if [ $i -lt $num ]; then
echo "
   data ${folders[$i]}-N_Cup.dat d6=c1,c2
   d6 line lstyle 3 marker triangle msize 0.3 color $color2Cup key \"${folders[$i]}: Cu^+\" " >> Ncompare.gle
tail -n 3 Ncompare.gle >> Ncompare_eCup.gle
fi
let i=i+1

if [ $i -lt $num ]; then
echo "
   data ${folders[$i]}-N_Cup.dat d7=c1,c2
   d7 line lstyle 3 marker diamond msize 0.3 color $color3Cup key \"${folders[$i]}: Cu^+\" " >> Ncompare.gle
tail -n 3 Ncompare.gle >> Ncompare_eCup.gle
fi
let i=i+1

if [ $i -lt $num ]; then
echo "
   data ${folders[$i]}-N_Cup.dat d8=c1,c2
   d8 line lstyle 3 marker square msize 0.3 color $color4Cup key \"${folders[$i]}: Cu^+\" " >> Ncompare.gle
tail -n 3 Ncompare.gle >> Ncompare_eCup.gle
fi
let i=i+1

###
i=0
###

if [ $i -lt $num ]; then
echo "
   data ${folders[$i]}-N_Cu.dat d9=c1,c2
   d9 line y2axis lstyle 5 marker circle msize 0.3 color $color1Cu key \"${folders[$i]}: Cu\" " >> Ncompare.gle
tail -n 3 Ncompare.gle >> Ncompare_Cu.gle-tmp
fi
let i=i+1

if [ $i -lt $num ]; then
echo "
   data ${folders[$i]}-N_Cu.dat d10=c1,c2
   d10 line y2axis lstyle 5 marker triangle msize 0.3 color $color2Cu key \"${folders[$i]}: Cu\" " >> Ncompare.gle
tail -n 3 Ncompare.gle >> Ncompare_Cu.gle-tmp
fi
let i=i+1

if [ $i -lt $num ]; then
echo "  
   data ${folders[$i]}-N_Cu.dat d11=c1,c2  
   d11 line y2axis lstyle 5 marker diamond msize 0.3 color $color3Cu key \"${folders[$i]}: Cu\" " >> Ncompare.gle 
tail -n 3 Ncompare.gle >> Ncompare_Cu.gle-tmp
fi
let i=i+1

if [ $i -lt $num ]; then
echo "  
   data ${folders[$i]}-N_Cu.dat d12=c1,c2  
   d12 line y2axis lstyle 5 marker square msize 0.3 color $color4Cu key \"${folders[$i]}: Cu\" " >> Ncompare.gle 
tail -n 3 Ncompare.gle >> Ncompare_Cu.gle-tmp
fi
let i=i+1

sed s/y2axis/''/ Ncompare_Cu.gle-tmp >Ncompare_Cu.gle
rm Ncompare_Cu.gle-tmp

cp Ncompare.gle Ncompare_small.gle

echo "
   key pos br compact

   !xaxis min 0.1 max 0.75
   !yaxis min 0 max 600000
   !xaxis nticks 4
   !yaxis nticks 4

   xlabels hei 0.7
   ylabels hei 0.7

   !title "" hei 0.7
   ytitle \"Number of e^-, Cu^+ \"  dist 0.4 hei 0.6
   y2title \"Number of Cu \"  dist 0.4 hei 0.6
   xtitle \"Time [ns]\"  dist 0.4 hei 0.6
   
end graph " >> Ncompare.gle 

echo "
   key pos br compact

   !xaxis min 0.1 max 0.75
   !yaxis min 0 max 600000
   !xaxis nticks 4
   !yaxis nticks 4

   xlabels hei 0.7
   ylabels hei 0.7

   !title "" hei 0.7
   ytitle \"Number of particles\"  dist 0.4 hei 0.6
   xtitle \"Time [ns]\"  dist 0.4 hei 0.6
   
end graph " >> Ncompare_Cu.gle 
tail -n 16 Ncompare_Cu.gle >> Ncompare_eCup.gle 

echo "
   key pos tl compact

   xaxis min 0 max 1.0
!   yaxis min 0 max 300000
   xaxis nticks 4
   yaxis nticks 4

   xlabels hei 0.7
   ylabels hei 0.7

   !title "" hei 0.7
   ytitle \"Number of particles\"  dist 0.4 hei 0.6
   xtitle \"Time [ns]\"  dist 0.4 hei 0.6
   
end graph
" >> Ncompare_small.gle   


gle -d png -r 100 -o Ncomp_${string} Ncompare.gle
gle -d png -o Ncomp_${string}_small Ncompare_small.gle
gle -d png -o Ncomp_${string}_eCup Ncompare_eCup.gle
gle -d png -o Ncomp_${string}_Cu Ncompare_Cu.gle

cp Ncomp_${string}.png ../
